#pragma once
#include "cex.h"
#include "libevdev/libevdev.h"
#include <linux/input-event-codes.h>
#include <linux/uinput.h>

typedef struct KeyMap_c
{
    struct
    {
        struct libevdev* dev;
        int fd;
    } input;

    struct
    {
        int fd;
    } output;

    struct
    {
        struct libevdev_uinput *dev;
        u64 last_press_ts;
        bool up;
        bool down;
        bool left;
        bool right;
    } mouse;

    bool debug;
    bool mod_pressed;
    bool mouse_pressed;
    f32 mouse_sensitivity;
    u64 mouse_speedup_ms;
    u16 mod_key_code;
    u16 mouse_key_code;
    u16 last_key_mod;
    u16 direct_map[KEY_CNT];
    u16 mod_map[KEY_CNT];
    u16 mouse_map[KEY_CNT];
} KeyMap_c;

struct __cex_namespace__KeyMap {
    // Autogenerated by CEX
    // clang-format off

    Exception       (*create)(KeyMap_c* self, char* input_dev_or_name);
    void            (*destroy)(KeyMap_c* self);
    Exception       (*find_mapped_keyboard)(KeyMap_c* self, char* keyboard_name);
    Exception       (*handle_events)(KeyMap_c* self);
    Exception       (*handle_key)(KeyMap_c* self, struct input_event* ev);
    Exception       (*handle_mouse_move)(KeyMap_c* self);
    bool            (*is_qwerty_keyboard)(struct libevdev* dev);
    Exception       (*mouse_click)(KeyMap_c* self, int button, int pressed);
    Exception       (*mouse_movement)(KeyMap_c* self, int rel_x, int rel_y);
    Exception       (*mouse_wheel)(KeyMap_c* self, int vertical);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__KeyMap KeyMap;

