#pragma once
#include "cex.h"
#include "libevdev/libevdev.h"
#include <linux/input-event-codes.h>
#include <linux/uinput.h>

typedef struct KeyMap_c
{
    struct
    {
        struct libevdev* dev;
        int fd;
    } input;

    struct
    {
        int fd;
    } output;

    bool debug;
    bool mod_pressed;
    u16 mod_key_code;
    u16 direct_map[KEY_CNT];
    u16 mod_map[KEY_CNT];
} KeyMap_c;

struct __cex_namespace__KeyMap {
    // Autogenerated by CEX
    // clang-format off

    Exception       (*create)(KeyMap_c* self, char* input_dev);
    void            (*destroy)(KeyMap_c* self);
    Exception       (*handle_events)(KeyMap_c* self);
    Exception       (*handle_key)(KeyMap_c* self, struct input_event* ev);

    // clang-format on
};
CEX_NAMESPACE struct __cex_namespace__KeyMap KeyMap;

